[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "flowprep"
version = "0.1.0"
description = "Utilities for aortic model flow split preprocessing"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "meshio>=5.3.5",
    "numpy>=2.5.0",
    "pynrrd>=1.1.3",
    "pyvista>=0.48.4",
    "scipy>=1.18.0",
]

[project.scripts]
nrrd2vti = "flowprep.nrrd_to_vti:main"
flowfilter = "flowprep.flow_filter:main"


[dependency-groups]
dev = ["jupyter>=1.1.1", "ruff>=0.15.18"]
